apiVersion: v1
kind: Service
metadata:
  labels:
    app: server
  name: web-server
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 9000
    targetPort: 9000
  selector:
    app: server
